name: link-learn
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python = 3
  - pandas
  - numpy
  - scikit-learn
  - libnetworkit
  - graph-tool
  - networkx
  - python-infomap
  - python-louvain
  - pip
  - pip:
      - tensorflow==2.13
      - littleballoffur